#!/usr/bin/env python3
"""Generate localization JSON files for jokester-deck."""

from __future__ import annotations

import json
from pathlib import Path

RESOURCES = Path(__file__).resolve().parent.parent / "jokester-deck" / "Resources"
UI_LANGUAGES = ["en", "uk", "he", "ru", "ar", "zh", "fr", "de", "es", "ja"]
TRANSLATED_LANGS = ["uk", "he", "ru", "ar", "zh", "fr", "de", "es", "ja"]

UI_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "tab.home": "Home",
        "tab.codex": "Codex",
        "tab.demo": "Demo",
        "tab.trivia": "Trivia",
        "tab.collection": "Collection",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Featured Game",
        "stat.games": "Games",
        "stat.mastered": "Mastered",
        "stat.xp": "XP",
        "quote.dailyWisdom": "Daily Wisdom",
        "library.title": "Game Library",
        "filter.all": "All",
        "filter.twoPlayers": "2 Players",
        "filter.groups": "Groups",
        "filter.solo": "Solo",
        "filter.classic": "Classic",
        "search.games": "Search games…",
        "demo.dealAgain": "Deal Again",
        "demo.howToPlay": "How to Play",
        "demo.tapToDeal": "Tap to deal",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Score",
        "trivia.roundComplete": "Round Complete",
        "trivia.playAgain": "Play Again",
        "trivia.retry": "Retry",
        "trivia.loadError": "Could not load trivia",
        "trivia.xpEarned": "XP Earned",
        "trivia.offlinePack": "Offline Question Pack",
        "collection.level": "Level",
        "collection.strategyTips": "Strategy Tips",
        "collection.mastery": "Mastery",
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.languageDescription": "Choose your preferred language for the app interface and game content.",
        "category.classic": "Classic",
        "category.family": "Family",
        "category.strategy": "Strategy",
        "category.trick_taking": "Trick-Taking",
        "common.offline": "Offline",
        "common.done": "Done",
        "common.ok": "OK",
        "common.error": "Error",
        "common.players": "Players",
        "stat.unlocked": "Unlocked",
        "unlock.banner": "Reach level %@ to unlock %@ of %@ games",
        "unlock.levelRequired": "Reach level %@ to unlock this game",
        "unlock.lockedByLevel": "Level locked",
    },
    "uk": {
        "tab.home": "Головна",
        "tab.codex": "Кодекс",
        "tab.demo": "Демо",
        "tab.trivia": "Вікторина",
        "tab.collection": "Колекція",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Рекомендована гра",
        "stat.games": "Ігри",
        "stat.mastered": "Опановано",
        "stat.xp": "Досвід",
        "quote.dailyWisdom": "Мудрість дня",
        "library.title": "Бібліотека ігор",
        "filter.all": "Усі",
        "filter.twoPlayers": "2 гравці",
        "filter.groups": "Групи",
        "filter.solo": "Соло",
        "filter.classic": "Класика",
        "search.games": "Пошук ігор…",
        "demo.dealAgain": "Роздати знову",
        "demo.howToPlay": "Як грати",
        "demo.tapToDeal": "Торкніться, щоб роздати",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Рахунок",
        "trivia.roundComplete": "Раунд завершено",
        "trivia.playAgain": "Грати знову",
        "trivia.retry": "Повторити",
        "trivia.loadError": "Не вдалося завантажити вікторину",
        "trivia.xpEarned": "Отримано досвіду",
        "trivia.offlinePack": "Офлайн-пакет запитань",
        "collection.level": "Рівень",
        "collection.strategyTips": "Поради зі стратегії",
        "collection.mastery": "Майстерність",
        "settings.title": "Налаштування",
        "settings.language": "Мова",
        "settings.languageDescription": "Оберіть бажану мову для інтерфейсу та ігрового контенту.",
        "category.classic": "Класика",
        "category.family": "Сімейні",
        "category.strategy": "Стратегія",
        "category.trick_taking": "Взятки",
        "common.offline": "Офлайн",
        "common.done": "Готово",
        "common.ok": "OK",
        "common.error": "Помилка",
        "common.players": "Гравці",
        "stat.unlocked": "Відкрито",
        "unlock.banner": "Досягніть рівня %@, щоб відкрити %@ з %@ ігор",
        "unlock.levelRequired": "Досягніть рівня %@, щоб відкрити цю гру",
        "unlock.lockedByLevel": "Заблоковано рівнем",
    },
    "he": {
        "tab.home": "בית",
        "tab.codex": "קודקס",
        "tab.demo": "הדגמה",
        "tab.trivia": "חידון",
        "tab.collection": "אוסף",
        "home.title": "Jokester Deck",
        "home.featuredGame": "משחק מומלץ",
        "stat.games": "משחקים",
        "stat.mastered": "שולט",
        "stat.xp": "נקודות",
        "quote.dailyWisdom": "חוכמת היום",
        "library.title": "ספריית משחקים",
        "filter.all": "הכל",
        "filter.twoPlayers": "2 שחקנים",
        "filter.groups": "קבוצות",
        "filter.solo": "סולו",
        "filter.classic": "קלאסי",
        "search.games": "חיפוש משחקים…",
        "demo.dealAgain": "חלק שוב",
        "demo.howToPlay": "איך משחקים",
        "demo.tapToDeal": "הקש כדי לחלק",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "ניקוד",
        "trivia.roundComplete": "הסיבוב הסתיים",
        "trivia.playAgain": "שחק שוב",
        "trivia.retry": "נסה שוב",
        "trivia.loadError": "לא ניתן לטעון חידון",
        "trivia.xpEarned": "נקודות שנצברו",
        "trivia.offlinePack": "חבילת שאלות לא מקוון",
        "collection.level": "רמה",
        "collection.strategyTips": "טיפים אסטרטגיים",
        "collection.mastery": "שליטה",
        "settings.title": "הגדרות",
        "settings.language": "שפה",
        "settings.languageDescription": "בחרו את השפה המועדפת עבור הממשק ותוכן המשחקים.",
        "category.classic": "קלאסי",
        "category.family": "משפחתי",
        "category.strategy": "אסטרטגיה",
        "category.trick_taking": "משחקי לקיחות",
        "common.offline": "לא מקוון",
        "common.done": "סיום",
        "common.ok": "אישור",
        "common.error": "שגיאה",
        "common.players": "שחקנים",
        "stat.unlocked": "נפתח",
        "unlock.banner": "הגיעו לרמה %@ כדי לפתוח %@ מתוך %@ משחקים",
        "unlock.levelRequired": "הגיעו לרמה %@ כדי לפתוח משחק זה",
        "unlock.lockedByLevel": "נעול לפי רמה",
    },
    "ru": {
        "tab.home": "Главная",
        "tab.codex": "Кодекс",
        "tab.demo": "Демо",
        "tab.trivia": "Викторина",
        "tab.collection": "Коллекция",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Рекомендуемая игра",
        "stat.games": "Игры",
        "stat.mastered": "Освоено",
        "stat.xp": "Опыт",
        "quote.dailyWisdom": "Мудрость дня",
        "library.title": "Библиотека игр",
        "filter.all": "Все",
        "filter.twoPlayers": "2 игрока",
        "filter.groups": "Группы",
        "filter.solo": "Соло",
        "filter.classic": "Классика",
        "search.games": "Поиск игр…",
        "demo.dealAgain": "Раздать снова",
        "demo.howToPlay": "Как играть",
        "demo.tapToDeal": "Нажмите, чтобы раздать",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Счёт",
        "trivia.roundComplete": "Раунд завершён",
        "trivia.playAgain": "Играть снова",
        "trivia.retry": "Повторить",
        "trivia.loadError": "Не удалось загрузить викторину",
        "trivia.xpEarned": "Получено опыта",
        "trivia.offlinePack": "Офлайн-набор вопросов",
        "collection.level": "Уровень",
        "collection.strategyTips": "Советы по стратегии",
        "collection.mastery": "Мастерство",
        "settings.title": "Настройки",
        "settings.language": "Язык",
        "settings.languageDescription": "Выберите предпочитаемый язык интерфейса и игрового контента.",
        "category.classic": "Классика",
        "category.family": "Семейные",
        "category.strategy": "Стратегия",
        "category.trick_taking": "Взятки",
        "common.offline": "Офлайн",
        "common.done": "Готово",
        "common.ok": "OK",
        "common.error": "Ошибка",
        "common.players": "Игроки",
        "stat.unlocked": "Открыто",
        "unlock.banner": "Достигните уровня %@, чтобы открыть %@ из %@ игр",
        "unlock.levelRequired": "Достигните уровня %@, чтобы открыть эту игру",
        "unlock.lockedByLevel": "Заблокировано уровнем",
    },
    "ar": {
        "tab.home": "الرئيسية",
        "tab.codex": "الموسوعة",
        "tab.demo": "تجربة",
        "tab.trivia": "أسئلة",
        "tab.collection": "المجموعة",
        "home.title": "Jokester Deck",
        "home.featuredGame": "لعبة مميزة",
        "stat.games": "الألعاب",
        "stat.mastered": "متقن",
        "stat.xp": "نقاط الخبرة",
        "quote.dailyWisdom": "حكمة اليوم",
        "library.title": "مكتبة الألعاب",
        "filter.all": "الكل",
        "filter.twoPlayers": "لاعبان",
        "filter.groups": "مجموعات",
        "filter.solo": "فردي",
        "filter.classic": "كلاسيكي",
        "search.games": "البحث عن ألعاب…",
        "demo.dealAgain": "وزّع مرة أخرى",
        "demo.howToPlay": "كيفية اللعب",
        "demo.tapToDeal": "اضغط للتوزيع",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "النتيجة",
        "trivia.roundComplete": "انتهت الجولة",
        "trivia.playAgain": "العب مجدداً",
        "trivia.retry": "إعادة المحاولة",
        "trivia.loadError": "تعذّر تحميل الأسئلة",
        "trivia.xpEarned": "نقاط خبرة مكتسبة",
        "trivia.offlinePack": "حزمة أسئلة دون اتصال",
        "collection.level": "المستوى",
        "collection.strategyTips": "نصائح استراتيجية",
        "collection.mastery": "الإتقان",
        "settings.title": "الإعدادات",
        "settings.language": "اللغة",
        "settings.languageDescription": "اختر لغتك المفضلة لواجهة التطبيق ومحتوى الألعاب.",
        "category.classic": "كلاسيكي",
        "category.family": "عائلية",
        "category.strategy": "استراتيجية",
        "category.trick_taking": "أخذ الأوراق",
        "common.offline": "دون اتصال",
        "common.done": "تم",
        "common.ok": "موافق",
        "common.error": "خطأ",
        "common.players": "اللاعبون",
        "stat.unlocked": "مفتوح",
        "unlock.banner": "بلغ المستوى %@ لفتح %@ من %@ لعبة",
        "unlock.levelRequired": "بلغ المستوى %@ لفتح هذه اللعبة",
        "unlock.lockedByLevel": "مقفل بالمستوى",
    },
    "zh": {
        "tab.home": "首页",
        "tab.codex": "图鉴",
        "tab.demo": "演示",
        "tab.trivia": "问答",
        "tab.collection": "收藏",
        "home.title": "Jokester Deck",
        "home.featuredGame": "精选游戏",
        "stat.games": "游戏",
        "stat.mastered": "已掌握",
        "stat.xp": "经验",
        "quote.dailyWisdom": "每日格言",
        "library.title": "游戏库",
        "filter.all": "全部",
        "filter.twoPlayers": "双人",
        "filter.groups": "多人",
        "filter.solo": "单人",
        "filter.classic": "经典",
        "search.games": "搜索游戏…",
        "demo.dealAgain": "重新发牌",
        "demo.howToPlay": "玩法说明",
        "demo.tapToDeal": "点击发牌",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "得分",
        "trivia.roundComplete": "本轮结束",
        "trivia.playAgain": "再玩一次",
        "trivia.retry": "重试",
        "trivia.loadError": "无法加载问答",
        "trivia.xpEarned": "获得经验",
        "trivia.offlinePack": "离线题库",
        "collection.level": "等级",
        "collection.strategyTips": "策略提示",
        "collection.mastery": "精通度",
        "settings.title": "设置",
        "settings.language": "语言",
        "settings.languageDescription": "选择应用界面和游戏内容的首选语言。",
        "category.classic": "经典",
        "category.family": "家庭",
        "category.strategy": "策略",
        "category.trick_taking": "吃墩",
        "common.offline": "离线",
        "common.done": "完成",
        "common.ok": "确定",
        "common.error": "错误",
        "common.players": "玩家",
        "stat.unlocked": "已解锁",
        "unlock.banner": "达到等级 %@ 可解锁 %@ / %@ 款游戏",
        "unlock.levelRequired": "达到等级 %@ 可解锁此游戏",
        "unlock.lockedByLevel": "等级锁定",
    },
    "fr": {
        "tab.home": "Accueil",
        "tab.codex": "Codex",
        "tab.demo": "Démo",
        "tab.trivia": "Quiz",
        "tab.collection": "Collection",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Jeu à la une",
        "stat.games": "Jeux",
        "stat.mastered": "Maîtrisés",
        "stat.xp": "XP",
        "quote.dailyWisdom": "Sagesse du jour",
        "library.title": "Bibliothèque de jeux",
        "filter.all": "Tous",
        "filter.twoPlayers": "2 joueurs",
        "filter.groups": "Groupes",
        "filter.solo": "Solo",
        "filter.classic": "Classique",
        "search.games": "Rechercher des jeux…",
        "demo.dealAgain": "Redistribuer",
        "demo.howToPlay": "Comment jouer",
        "demo.tapToDeal": "Appuyez pour distribuer",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Score",
        "trivia.roundComplete": "Manche terminée",
        "trivia.playAgain": "Rejouer",
        "trivia.retry": "Réessayer",
        "trivia.loadError": "Impossible de charger le quiz",
        "trivia.xpEarned": "XP gagnés",
        "trivia.offlinePack": "Pack de questions hors ligne",
        "collection.level": "Niveau",
        "collection.strategyTips": "Conseils stratégiques",
        "collection.mastery": "Maîtrise",
        "settings.title": "Réglages",
        "settings.language": "Langue",
        "settings.languageDescription": "Choisissez votre langue préférée pour l'interface et le contenu des jeux.",
        "category.classic": "Classique",
        "category.family": "Famille",
        "category.strategy": "Stratégie",
        "category.trick_taking": "Levées",
        "common.offline": "Hors ligne",
        "common.done": "Terminé",
        "common.ok": "OK",
        "common.error": "Erreur",
        "common.players": "Joueurs",
        "stat.unlocked": "Débloqués",
        "unlock.banner": "Atteignez le niveau %@ pour débloquer %@ jeux sur %@",
        "unlock.levelRequired": "Atteignez le niveau %@ pour débloquer ce jeu",
        "unlock.lockedByLevel": "Verrouillé par niveau",
    },
    "de": {
        "tab.home": "Start",
        "tab.codex": "Kodex",
        "tab.demo": "Demo",
        "tab.trivia": "Quiz",
        "tab.collection": "Sammlung",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Empfohlenes Spiel",
        "stat.games": "Spiele",
        "stat.mastered": "Gemeistert",
        "stat.xp": "EP",
        "quote.dailyWisdom": "Weisheit des Tages",
        "library.title": "Spielebibliothek",
        "filter.all": "Alle",
        "filter.twoPlayers": "2 Spieler",
        "filter.groups": "Gruppen",
        "filter.solo": "Solo",
        "filter.classic": "Klassisch",
        "search.games": "Spiele suchen…",
        "demo.dealAgain": "Neu verteilen",
        "demo.howToPlay": "Spielanleitung",
        "demo.tapToDeal": "Tippen zum Verteilen",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Punkte",
        "trivia.roundComplete": "Runde beendet",
        "trivia.retry": "Erneut versuchen",
        "trivia.playAgain": "Nochmal spielen",
        "trivia.loadError": "Quiz konnte nicht geladen werden",
        "trivia.xpEarned": "EP verdient",
        "trivia.offlinePack": "Offline-Fragenpaket",
        "collection.level": "Level",
        "collection.strategyTips": "Strategietipps",
        "collection.mastery": "Meisterschaft",
        "settings.title": "Einstellungen",
        "settings.language": "Sprache",
        "settings.languageDescription": "Wählen Sie Ihre bevorzugte Sprache für Oberfläche und Spielinhalte.",
        "category.classic": "Klassisch",
        "category.family": "Familie",
        "category.strategy": "Strategie",
        "category.trick_taking": "Stichspiele",
        "common.offline": "Offline",
        "common.done": "Fertig",
        "common.ok": "OK",
        "common.error": "Fehler",
        "common.players": "Spieler",
        "stat.unlocked": "Freigeschaltet",
        "unlock.banner": "Erreiche Level %@, um %@ von %@ Spielen freizuschalten",
        "unlock.levelRequired": "Erreiche Level %@, um dieses Spiel freizuschalten",
        "unlock.lockedByLevel": "Level gesperrt",
    },
    "es": {
        "tab.home": "Inicio",
        "tab.codex": "Códice",
        "tab.demo": "Demo",
        "tab.trivia": "Trivia",
        "tab.collection": "Colección",
        "home.title": "Jokester Deck",
        "home.featuredGame": "Juego destacado",
        "stat.games": "Juegos",
        "stat.mastered": "Dominados",
        "stat.xp": "XP",
        "quote.dailyWisdom": "Sabiduría del día",
        "library.title": "Biblioteca de juegos",
        "filter.all": "Todos",
        "filter.twoPlayers": "2 jugadores",
        "filter.groups": "Grupos",
        "filter.solo": "Solo",
        "filter.classic": "Clásico",
        "search.games": "Buscar juegos…",
        "demo.dealAgain": "Repartir de nuevo",
        "demo.howToPlay": "Cómo jugar",
        "demo.tapToDeal": "Toca para repartir",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "Puntuación",
        "trivia.roundComplete": "Ronda completada",
        "trivia.playAgain": "Jugar de nuevo",
        "trivia.retry": "Reintentar",
        "trivia.loadError": "No se pudo cargar la trivia",
        "trivia.xpEarned": "XP ganados",
        "trivia.offlinePack": "Paquete de preguntas sin conexión",
        "collection.level": "Nivel",
        "collection.strategyTips": "Consejos estratégicos",
        "collection.mastery": "Dominio",
        "settings.title": "Ajustes",
        "settings.language": "Idioma",
        "settings.languageDescription": "Elige tu idioma preferido para la interfaz y el contenido de los juegos.",
        "category.classic": "Clásico",
        "category.family": "Familia",
        "category.strategy": "Estrategia",
        "category.trick_taking": "Bazas",
        "common.offline": "Sin conexión",
        "common.done": "Listo",
        "common.ok": "OK",
        "common.error": "Error",
        "common.players": "Jugadores",
        "stat.unlocked": "Desbloqueados",
        "unlock.banner": "Alcanza el nivel %@ para desbloquear %@ de %@ juegos",
        "unlock.levelRequired": "Alcanza el nivel %@ para desbloquear este juego",
        "unlock.lockedByLevel": "Bloqueado por nivel",
    },
    "ja": {
        "tab.home": "ホーム",
        "tab.codex": "コデックス",
        "tab.demo": "デモ",
        "tab.trivia": "クイズ",
        "tab.collection": "コレクション",
        "home.title": "Jokester Deck",
        "home.featuredGame": "おすすめゲーム",
        "stat.games": "ゲーム",
        "stat.mastered": "習得",
        "stat.xp": "XP",
        "quote.dailyWisdom": "今日の格言",
        "library.title": "ゲームライブラリ",
        "filter.all": "すべて",
        "filter.twoPlayers": "2人",
        "filter.groups": "グループ",
        "filter.solo": "ソロ",
        "filter.classic": "クラシック",
        "search.games": "ゲームを検索…",
        "demo.dealAgain": "もう一度配る",
        "demo.howToPlay": "遊び方",
        "demo.tapToDeal": "タップして配る",
        "demo.playersCategory": "%@–%@ · %@",
        "trivia.score": "スコア",
        "trivia.roundComplete": "ラウンド終了",
        "trivia.playAgain": "もう一度",
        "trivia.retry": "再試行",
        "trivia.loadError": "クイズを読み込めませんでした",
        "trivia.xpEarned": "獲得XP",
        "trivia.offlinePack": "オフライン問題パック",
        "collection.level": "レベル",
        "collection.strategyTips": "戦略のヒント",
        "collection.mastery": "習熟度",
        "settings.title": "設定",
        "settings.language": "言語",
        "settings.languageDescription": "アプリの表示とゲーム内容の言語を選択してください。",
        "category.classic": "クラシック",
        "category.family": "ファミリー",
        "category.strategy": "ストラテジー",
        "category.trick_taking": "トリックテイキング",
        "common.offline": "オフライン",
        "common.done": "完了",
        "common.ok": "OK",
        "common.error": "エラー",
        "common.players": "プレイヤー",
        "stat.unlocked": "解放",
        "unlock.banner": "レベル %@ で %@ / %@ ゲームが解放されます",
        "unlock.levelRequired": "レベル %@ でこのゲームが解放されます",
        "unlock.lockedByLevel": "レベルロック",
    },
}

QUOTES: dict[str, list[dict[str, str]]] = {
    "en": [
        {"content": "Life is like a deck of cards. You play the hand you're dealt.", "author": "Unknown"},
        {"content": "A card game is a conversation between players.", "author": "Unknown"},
        {"content": "Strategy is knowing what to do when you don't know what to do.", "author": "Unknown"},
        {"content": "Every master was once a beginner who refused to give up.", "author": "Unknown"},
        {"content": "The joker reminds us that rules can bend when creativity leads.", "author": "Unknown"},
        {"content": "Patience at the table teaches patience in life.", "author": "Unknown"},
        {"content": "A good player reads the game, not just the cards.", "author": "Unknown"},
        {"content": "Learning the rules is the first step to mastering any game.", "author": "Unknown"},
        {"content": "Fortune favors the prepared mind at the card table.", "author": "Unknown"},
        {"content": "Play fair, think clearly, and enjoy the company.", "author": "Unknown"},
    ],
    "uk": [
        {"content": "Життя схоже на колоду карт. Граєш ті, що випали.", "author": "Невідомий"},
        {"content": "Карткова гра — це розмова між гравцями.", "author": "Невідомий"},
        {"content": "Стратегія — знати, що робити, коли не знаєш, що робити.", "author": "Невідомий"},
        {"content": "Кожен майстер колись був новачком, який не здавався.", "author": "Невідомий"},
        {"content": "Джокер нагадує, що правила можуть гнутися, коли веде творчість.", "author": "Невідомий"},
        {"content": "Терпіння за столом вчить терпінню в житті.", "author": "Невідомий"},
        {"content": "Хороший гравець читає гру, а не лише карти.", "author": "Невідомий"},
        {"content": "Вивчення правил — перший крок до майстерності.", "author": "Невідомий"},
        {"content": "Удача супроводжує підготовлений розум за столом.", "author": "Невідомий"},
        {"content": "Грайте чесно, думайте ясно і насолоджуйтесь компанією.", "author": "Невідомий"},
    ],
    "he": [
        {"content": "החיים דומים לחפיסת קלפים. משחקים את מה שחולקו לך.", "author": "לא ידוע"},
        {"content": "משחק קלפים הוא שיחה בין שחקנים.", "author": "לא ידוע"},
        {"content": "אסטרטגיה היא לדעת מה לעשות כשאינך יודע מה לעשות.", "author": "לא ידוע"},
        {"content": "כל מומחה היה פעם מתחיל שסירב לוותר.", "author": "לא ידוע"},
        {"content": "הג'וקר מזכיר לנו שכללים יכולים להתגמש כשיצירתיות מובילה.", "author": "לא ידוע"},
        {"content": "סבלנות ליד השולחן מלמדת סבלנות בחיים.", "author": "לא ידוע"},
        {"content": "שחקן טוב קורא את המשחק, לא רק את הקלפים.", "author": "לא ידוע"},
        {"content": "לימוד הכללים הוא הצעד הראשון לשליטה בכל משחק.", "author": "לא ידוע"},
        {"content": "מזל מעדיף את המוח המוכן ליד שולחן הקלפים.", "author": "לא ידוע"},
        {"content": "שחקו הוגן, חשבו בבהירות ותהנו מהחברה.", "author": "לא ידוע"},
    ],
    "ru": [
        {"content": "Жизнь похожа на колоду карт. Играешь тем, что раздали.", "author": "Неизвестно"},
        {"content": "Карточная игра — это разговор между игроками.", "author": "Неизвестно"},
        {"content": "Стратегия — знать, что делать, когда не знаешь, что делать.", "author": "Неизвестно"},
        {"content": "Каждый мастер когда-то был новичком, который не сдавался.", "author": "Неизвестно"},
        {"content": "Джокер напоминает, что правила могут гнуться, когда ведёт творчество.", "author": "Неизвестно"},
        {"content": "Терпение за столом учит терпению в жизни.", "author": "Неизвестно"},
        {"content": "Хороший игрок читает игру, а не только карты.", "author": "Неизвестно"},
        {"content": "Изучение правил — первый шаг к мастерству.", "author": "Неизвестно"},
        {"content": "Удача благоприятствует подготовленному уму за столом.", "author": "Неизвестно"},
        {"content": "Играйте честно, думайте ясно и наслаждайтесь компанией.", "author": "Неизвестно"},
    ],
    "ar": [
        {"content": "الحياة مثل مجموعة أوراق. تلعب ما يُوزَّع عليك.", "author": "مجهول"},
        {"content": "لعبة الورق محادثة بين اللاعبين.", "author": "مجهول"},
        {"content": "الاستراتيجية هي معرفة ماذا تفعل عندما لا تعرف.", "author": "مجهول"},
        {"content": "كل خبير كان مبتدئاً رفض الاستسلام.", "author": "مجهول"},
        {"content": "الجوكر يذكّرنا أن القواعد قد تتغيّر حين تقود الإبداع.", "author": "مجهول"},
        {"content": "الصبر على الطاولة يعلّم الصبر في الحياة.", "author": "مجهول"},
        {"content": "اللاعب الجيد يقرأ اللعبة لا الأوراق فقط.", "author": "مجهول"},
        {"content": "تعلّم القواعد هو الخطوة الأولى لإتقان أي لعبة.", "author": "مجهول"},
        {"content": "الحظ يحبّ العقل المستعد على طاولة الورق.", "author": "مجهول"},
        {"content": "العب بإنصاف، فكّر بوضوح، واستمتع بالرفقة.", "author": "مجهول"},
    ],
    "zh": [
        {"content": "生活就像一副牌，你只能打好发到手中的牌。", "author": "未知"},
        {"content": "纸牌游戏是玩家之间的对话。", "author": "未知"},
        {"content": "策略就是在不知所措时仍知道该怎么做。", "author": "未知"},
        {"content": "每位高手都曾是不肯放弃的新手。", "author": "未知"},
        {"content": "小丑提醒我们，创造力可以灵活变通规则。", "author": "未知"},
        {"content": "牌桌上的耐心也教会生活中的耐心。", "author": "未知"},
        {"content": "好玩家读的是局势，而不只是牌面。", "author": "未知"},
        {"content": "学习规则是掌握任何游戏的第一步。", "author": "未知"},
        {"content": "牌桌上，幸运青睐有准备的人。", "author": "未知"},
        {"content": "公平游戏，清晰思考，享受陪伴。", "author": "未知"},
    ],
    "fr": [
        {"content": "La vie ressemble à un jeu de cartes : on joue la main qu'on reçoit.", "author": "Inconnu"},
        {"content": "Un jeu de cartes est une conversation entre joueurs.", "author": "Inconnu"},
        {"content": "La stratégie, c'est savoir quoi faire quand on ne sait pas.", "author": "Inconnu"},
        {"content": "Tout maître fut un jour un débutant qui n'a pas abandonné.", "author": "Inconnu"},
        {"content": "Le joker rappelle que les règles peuvent plier sous la créativité.", "author": "Inconnu"},
        {"content": "La patience à la table enseigne la patience dans la vie.", "author": "Inconnu"},
        {"content": "Un bon joueur lit la partie, pas seulement les cartes.", "author": "Inconnu"},
        {"content": "Apprendre les règles est la première étape vers la maîtrise.", "author": "Inconnu"},
        {"content": "La chance favorise l'esprit préparé autour de la table.", "author": "Inconnu"},
        {"content": "Jouez fair-play, pensez clairement et profitez de la compagnie.", "author": "Inconnu"},
    ],
    "de": [
        {"content": "Das Leben gleicht einem Kartenspiel – man spielt die ausgeteilte Hand.", "author": "Unbekannt"},
        {"content": "Ein Kartenspiel ist ein Gespräch zwischen Spielern.", "author": "Unbekannt"},
        {"content": "Strategie heißt zu wissen, was zu tun ist, wenn man es nicht weiß.", "author": "Unbekannt"},
        {"content": "Jeder Meister war einmal ein Anfänger, der nicht aufgab.", "author": "Unbekannt"},
        {"content": "Der Joker erinnert uns, dass Regeln sich biegen können, wenn Kreativität führt.", "author": "Unbekannt"},
        {"content": "Geduld am Tisch lehrt Geduld im Leben.", "author": "Unbekannt"},
        {"content": "Ein guter Spieler liest das Spiel, nicht nur die Karten.", "author": "Unbekannt"},
        {"content": "Regeln lernen ist der erste Schritt zur Meisterschaft.", "author": "Unbekannt"},
        {"content": "Glück begünstigt den vorbereiteten Geist am Kartentisch.", "author": "Unbekannt"},
        {"content": "Spiele fair, denke klar und genieße die Gesellschaft.", "author": "Unbekannt"},
    ],
    "es": [
        {"content": "La vida es como un mazo de cartas: juegas la mano que te toca.", "author": "Desconocido"},
        {"content": "Un juego de cartas es una conversación entre jugadores.", "author": "Desconocido"},
        {"content": "La estrategia es saber qué hacer cuando no lo sabes.", "author": "Desconocido"},
        {"content": "Todo maestro fue alguna vez un principiante que no se rindió.", "author": "Desconocido"},
        {"content": "El comodín recuerda que las reglas pueden doblarse con creatividad.", "author": "Desconocido"},
        {"content": "La paciencia en la mesa enseña paciencia en la vida.", "author": "Desconocido"},
        {"content": "Un buen jugador lee la partida, no solo las cartas.", "author": "Desconocido"},
        {"content": "Aprender las reglas es el primer paso para dominar cualquier juego.", "author": "Desconocido"},
        {"content": "La fortuna favorece a la mente preparada en la mesa.", "author": "Desconocido"},
        {"content": "Juega limpio, piensa con claridad y disfruta la compañía.", "author": "Desconocido"},
    ],
    "ja": [
        {"content": "人生はトランプのよう。配られた手札で勝負する。", "author": "不明"},
        {"content": "カードゲームはプレイヤー同士の会話だ。", "author": "不明"},
        {"content": "戦略とは、わからないときに何をすべきか知ること。", "author": "不明"},
        {"content": "達人もかつては諦めなかった初心者だった。", "author": "不明"},
        {"content": "ジョーカーは創造性が導くとき、ルールも曲がることを教える。", "author": "不明"},
        {"content": "テーブルでの忍耐は人生の忍耐を教える。", "author": "不明"},
        {"content": "上手なプレイヤーはカードだけでなくゲーム全体を読む。", "author": "不明"},
        {"content": "ルールを学ぶことが、どんなゲームも極める第一歩。", "author": "不明"},
        {"content": "幸運は準備された心に味方する。", "author": "不明"},
        {"content": "公正に、冷静に、そして仲間を楽しもう。", "author": "不明"},
    ],
}

TRIVIA: dict[str, list[dict[str, object]]] = {
    "uk": [
        {"question": "Скільки карт у стандартній колоді?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "У грі «Черви» яка карта дає 13 штрафних очок?", "correctAnswer": "Дама пік", "incorrectAnswers": ["Туз черв", "Король бубен", "Дев'ятка треф"], "category": "Board Games"},
        {"question": "Яка гра відома як «пасьянс» у Solitaire?", "correctAnswer": "Класичний пасьянс Klondike", "incorrectAnswers": ["Рамі", "Брідж", "Пoker"], "category": "Board Games"},
        {"question": "У бриджі скільки гравців у команді?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "Яка масть найвища у більшості ігор «на взятки» без козиря?", "correctAnswer": "Масть, яку поклали першою", "incorrectAnswers": ["Завжди піки", "Завжди червi", "Козир завжди перемагає"], "category": "Board Games"},
        {"question": "У «Дурі» (Crazy Eights) яка карта дозволяє змінити масть?", "correctAnswer": "Вісімка", "incorrectAnswers": ["Туз", "Король", "Двійка"], "category": "Board Games"},
        {"question": "Скільки карт роздають на старт у класичному Рамі для двох гравців?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "У грі «Рибалка» (Go Fish) що роблять, коли суперник не має потрібного рангу?", "correctAnswer": "Кажуть «йди лови» і беруть з колоди", "incorrectAnswers": ["Пропускають хід", "Скидають карту", "Міняються ролями"], "category": "Board Games"},
        {"question": "У кріббіджі до скількох очок зазвичай грають?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "Яка фігурна карта часто є «джокером» у багатьох колодах?", "correctAnswer": "Додаткова карта поза чотирма мастями", "incorrectAnswers": ["Туз", "Король", "Валет"], "category": "Board Games"},
    ],
    "he": [
        {"question": "כמה קלפים יש בחפיסה סטנדרטית?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "במשחק Hearts, איזו קלף שווה 13 נקודות עונש?", "correctAnswer": "מלכת עלה", "incorrectAnswers": ["אס יהלום", "מלך תלתן", "תשע עלה"], "category": "Board Games"},
        {"question": "באיזה משחק מסדרים קלפים לפי צבע מ-ACE עד מלך?", "correctAnswer": "סוליטר", "incorrectAnswers": ["רמי", "גו-פиш", "מלחמה"], "category": "Board Games"},
        {"question": "במשחק Bridge, כמה שחקנים בכל קבוצה?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "ב-Crazy Eights, איזה קלף מאפשר לשנות צבע?", "correctAnswer": "8", "incorrectAnswers": ["אס", "מלך", "2"], "category": "Board Games"},
        {"question": "כמה קלפים מחלקים בתחילת רמי קלאסי לשני שחקנים?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "ב-Go Fish, מה קורה כשאין ליריב את הדירוג שביקשת?", "correctAnswer": "אומרים 'Go Fish' ולוקחים מהקופה", "incorrectAnswers": ["מדלגים על תור", "זורקים קלף", "מחליפים תפקידים"], "category": "Board Games"},
        {"question": "ב-Cribbage, לא כמה נקודות בדרך כלל משחקים?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "כמה צבעים יש בחפיסה רגילה?", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "במשחק War, מה קורה בתיקו?", "correctAnswer": "כל שחקן שם 3 קלפים הפוכים ואחד גלוי", "incorrectAnswers": ["מחלקים מחדש", "מדלגים", "שניהם מפסידים"], "category": "Board Games"},
    ],
    "ru": [
        {"question": "Сколько карт в стандартной колоде?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "В «Червях» какая карта даёт 13 штрафных очков?", "correctAnswer": "Дама пик", "incorrectAnswers": ["Туз червей", "Король бубен", "Девятка треф"], "category": "Board Games"},
        {"question": "В какой игре строят стопки от туза до короля по мастям?", "correctAnswer": "Пасьянс", "incorrectAnswers": ["Рамi", "Бридж", "Вист"], "category": "Board Games"},
        {"question": "Сколько игроков в одной команде в бридже?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "В «Дураке» (Crazy Eights) какая карта меняет масть?", "correctAnswer": "Восьмёрка", "incorrectAnswers": ["Туз", "Король", "Двойка"], "category": "Board Games"},
        {"question": "Сколько карт сдают в классическом Рummy на двоих?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "В «Акуле» (Go Fish) что делают, если у соперника нет нужного достоинства?", "correctAnswer": "Говорят «иди лови» и берут из колоды", "incorrectAnswers": ["Пропускают ход", "Сбрасывают карту", "Меняются ролями"], "category": "Board Games"},
        {"question": "До скольки очков обычно играют в криббидж?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "Сколько мастей в обычной колоде?", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "В «Войне» что происходит при ничьей?", "correctAnswer": "Каждый кладёт 3 карты рубашкой вверх и одну открыто", "incorrectAnswers": ["Пересдают", "Пропускают", "Оба проигрывают"], "category": "Board Games"},
    ],
    "ar": [
        {"question": "كم عدد الأوراق في مجموعة قياسية؟", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "في لعبة Hearts، أي ورقة تساوي 13 نقطة عقوبة؟", "correctAnswer": "ملكة البستوني", "incorrectAnswers": ["آس الديناري", "ملك السباتي", "تسعة السباتي"], "category": "Board Games"},
        {"question": "في أي لعبة ترتّب الأوراق من الآس إلى الملك حسب اللون؟", "correctAnswer": "السولitaire", "incorrectAnswers": ["رامي", "جسر", "حرب"], "category": "Board Games"},
        {"question": "في لعبة Bridge، كم لاعباً في كل فريق؟", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "في Crazy Eights، أي ورقة تغيّر اللون؟", "correctAnswer": "الثمانية", "incorrectAnswers": ["الآس", "الملك", "الاثنان"], "category": "Board Games"},
        {"question": "كم ورقة تُوزَّع في بداية الرامي الكلاسيكي للاعبين اثنين؟", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "في Go Fish، ماذا يحدث إذا لم يملك الخصم الرتبة المطلوبة؟", "correctAnswer": "يقول «اذهب صُد» ويسحب من الكومة", "incorrectAnswers": ["يتخطى دوره", "يرمي ورقة", "يتبادل الأدوار"], "category": "Board Games"},
        {"question": "في Cribbage، إلى كم نقطة تُلعب عادةً؟", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "كم عدد الألوان في مجموعة عادية؟", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "في لعبة War، ماذا يحدث عند التعادل؟", "correctAnswer": "يضع كل لاعب 3 أوراق مقلوبة وورقة واحدة مكشوفة", "incorrectAnswers": ["إعادة التوزيع", "تخطي الدور", "خسارة الطرفين"], "category": "Board Games"},
    ],
    "zh": [
        {"question": "标准扑克牌一副有多少张？", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "在红心大战中，哪张牌值13罚分？", "correctAnswer": "黑桃Q", "incorrectAnswers": ["红心A", "方块K", "梅花9"], "category": "Board Games"},
        {"question": "哪种游戏按花色从A排到K建堆？", "correctAnswer": "纸牌接龙", "incorrectAnswers": ["拉米", "Go Fish", "战争"], "category": "Board Games"},
        {"question": "桥牌中每队有几名玩家？", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "在疯狂八中，哪张牌可以换花色？", "correctAnswer": "8", "incorrectAnswers": ["A", "K", "2"], "category": "Board Games"},
        {"question": "经典拉米两人开局各发几张牌？", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "在Go Fish中，对方没有你要的点数怎么办？", "correctAnswer": "说「Go Fish」并从牌堆抽牌", "incorrectAnswers": ["跳过回合", "弃牌", "交换身份"], "category": "Board Games"},
        {"question": "克里比奇通常玩到多少分？", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "普通牌有几门花色？", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "在战争牌中，平局时怎么处理？", "correctAnswer": "各暗放3张再翻1张比大小", "incorrectAnswers": ["重新发牌", "跳过", "双方都输"], "category": "Board Games"},
    ],
    "fr": [
        {"question": "Combien de cartes dans un jeu standard ?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "Dans Hearts, quelle carte vaut 13 points de pénalité ?", "correctAnswer": "Dame de pique", "incorrectAnswers": ["As de cœur", "Roi de carreau", "Neuf de trèfle"], "category": "Board Games"},
        {"question": "Dans quel jeu construit-on des piles de l'as au roi par couleur ?", "correctAnswer": "Solitaire", "incorrectAnswers": ["Rami", "Go Fish", "Bataille"], "category": "Board Games"},
        {"question": "Au bridge, combien de joueurs par équipe ?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "Dans Crazy Eights, quelle carte change la couleur ?", "correctAnswer": "Le huit", "incorrectAnswers": ["L'as", "Le roi", "Le deux"], "category": "Board Games"},
        {"question": "Au rami classique à deux, combien de cartes au départ ?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "À Go Fish, que faire si l'adversaire n'a pas le rang demandé ?", "correctAnswer": "Dire « Go Fish » et piocher", "incorrectAnswers": ["Passer son tour", "Défausser", "Échanger les rôles"], "category": "Board Games"},
        {"question": "Au cribbage, on joue généralement jusqu'à combien de points ?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "Combien de couleurs dans un jeu ordinaire ?", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "À la bataille, que se passe-t-il en cas d'égalité ?", "correctAnswer": "Chacun pose 3 cartes face cachée puis 1 face visible", "incorrectAnswers": ["On redistribue", "On passe", "Les deux perdent"], "category": "Board Games"},
    ],
    "de": [
        {"question": "Wie viele Karten hat ein Standardspiel?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "Welche Karte bringt in Hearts 13 Minuspunkte?", "correctAnswer": "Pik-Dame", "incorrectAnswers": ["Herz-Ass", "Karo-König", "Kreuz-Neun"], "category": "Board Games"},
        {"question": "In welchem Spiel baut man Stapel vom Ass bis König pro Farbe?", "correctAnswer": "Solitaire", "incorrectAnswers": ["Rommé", "Go Fish", "Krieg"], "category": "Board Games"},
        {"question": "Wie viele Spieler hat ein Team beim Bridge?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "Welche Karte ändert die Farbe bei Crazy Eights?", "correctAnswer": "Die Acht", "incorrectAnswers": ["Das Ass", "Der König", "Die Zwei"], "category": "Board Games"},
        {"question": "Wie viele Karten erhält man zu Beginn beim klassischen Rommé zu zweit?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "Was passiert bei Go Fish, wenn der Gegner den Rang nicht hat?", "correctAnswer": "Man sagt «Go Fish» und zieht vom Stapel", "incorrectAnswers": ["Man passt", "Man wirft ab", "Man tauscht Rollen"], "category": "Board Games"},
        {"question": "Bis wie viele Punkte spielt man üblicherweise Cribbage?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "Wie viele Farben hat ein normales Kartenspiel?", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "Was passiert bei Gleichstand in War?", "correctAnswer": "Jeder legt 3 verdeckte und 1 offene Karte", "incorrectAnswers": ["Neu mischen", "Aussetzen", "Beide verlieren"], "category": "Board Games"},
    ],
    "es": [
        {"question": "¿Cuántas cartas tiene una baraja estándar?", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "En Hearts, ¿qué carta vale 13 puntos de penalización?", "correctAnswer": "Reina de picas", "incorrectAnswers": ["As de corazones", "Rey de diamantes", "Nueve de tréboles"], "category": "Board Games"},
        {"question": "¿En qué juego se apilan cartas del as al rey por palo?", "correctAnswer": "Solitario", "incorrectAnswers": ["Rummy", "Go Fish", "Guerra"], "category": "Board Games"},
        {"question": "En bridge, ¿cuántos jugadores hay por equipo?", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "En Crazy Eights, ¿qué carta cambia el palo?", "correctAnswer": "El ocho", "incorrectAnswers": ["El as", "El rey", "El dos"], "category": "Board Games"},
        {"question": "¿Cuántas cartas se reparten al inicio del rummy clásico para dos?", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "En Go Fish, ¿qué pasa si el rival no tiene el rango pedido?", "correctAnswer": "Se dice «Go Fish» y se roba del mazo", "incorrectAnswers": ["Se pasa el turno", "Se descarta", "Se intercambian roles"], "category": "Board Games"},
        {"question": "¿Hasta cuántos puntos se juega cribbage normalmente?", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "¿Cuántos palos tiene una baraja común?", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "En Guerra, ¿qué ocurre en un empate?", "correctAnswer": "Cada uno pone 3 cartas boca abajo y 1 boca arriba", "incorrectAnswers": ["Se reparte de nuevo", "Se salta", "Pierden ambos"], "category": "Board Games"},
    ],
    "ja": [
        {"question": "標準的なトランプ1組は何枚？", "correctAnswer": "52", "incorrectAnswers": ["48", "54", "50"], "category": "Board Games"},
        {"question": "ハーツで13ペナルティ点になるカードは？", "correctAnswer": "スペードのQ", "incorrectAnswers": ["ハートのA", "ダイヤのK", "クラブの9"], "category": "Board Games"},
        {"question": "スートごとにAからKまで積むゲームは？", "correctAnswer": "ソリティア", "incorrectAnswers": ["ラミー", "ゴーフィッシュ", "ウォー"], "category": "Board Games"},
        {"question": "ブリッジで1チームの人数は？", "correctAnswer": "2", "incorrectAnswers": ["3", "4", "1"], "category": "Board Games"},
        {"question": "クレイジー8でスートを変えられるカードは？", "correctAnswer": "8", "incorrectAnswers": ["A", "K", "2"], "category": "Board Games"},
        {"question": "クラシックラミー2人戦の初期配布枚数は？", "correctAnswer": "10", "incorrectAnswers": ["7", "5", "13"], "category": "Board Games"},
        {"question": "ゴーフィッシュで相手が求めたランクを持っていないときは？", "correctAnswer": "「Go Fish」と言って山札から引く", "incorrectAnswers": ["パスする", "捨てる", "役割を入れ替える"], "category": "Board Games"},
        {"question": "クリベッジは通常何点まで？", "correctAnswer": "121", "incorrectAnswers": ["100", "150", "50"], "category": "Board Games"},
        {"question": "普通のトランプのスート数は？", "correctAnswer": "4", "incorrectAnswers": ["3", "5", "6"], "category": "Board Games"},
        {"question": "ウォーで同点のときは？", "correctAnswer": "各プレイヤーが裏向き3枚と表1枚を出す", "incorrectAnswers": ["再配布", "スキップ", "両方負け"], "category": "Board Games"},
    ],
}


def _load_game_translations() -> dict[str, dict[str, dict]]:
    snippet_path = Path(__file__).resolve().parent / "_game_translations_snippet.py"
    namespace: dict = {}
    exec(snippet_path.read_text(encoding="utf-8"), namespace)  # noqa: S102
    return namespace["GAME_TRANSLATIONS"]


def write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def count_lines(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines())


def main() -> None:
    created: list[tuple[str, int]] = []

    ui_path = RESOURCES / "UIStrings.json"
    write_json(ui_path, UI_STRINGS)
    created.append((ui_path.name, count_lines(ui_path)))

    quotes_path = RESOURCES / "Quotes.json"
    write_json(quotes_path, QUOTES)
    created.append((quotes_path.name, count_lines(quotes_path)))

    games_en_path = RESOURCES / "games-en.json"
    with games_en_path.open(encoding="utf-8") as handle:
        games_en = json.load(handle)
    slugs = list(games_en.keys())

    game_translations = _load_game_translations()
    for lang in TRANSLATED_LANGS:
        lang_games = game_translations.get(lang, {})
        output = {}
        for slug in slugs:
            if slug in lang_games:
                output[slug] = lang_games[slug]
            elif slug in games_en:
                output[slug] = games_en[slug]
            else:
                raise SystemExit(f"Missing game content for slug: {slug}")
        path = RESOURCES / f"games-{lang}.json"
        write_json(path, output)
        created.append((path.name, count_lines(path)))

    for lang in TRANSLATED_LANGS:
        path = RESOURCES / f"trivia-{lang}.json"
        write_json(path, TRIVIA[lang])
        created.append((path.name, count_lines(path)))

    game_data_path = RESOURCES / "GameData.json"
    if game_data_path.exists():
        game_data_path.unlink()
        print(f"Deleted {game_data_path.name}")

    print("Generated localization files:")
    for name, lines in created:
        print(f"  {name}: {lines} lines")


if __name__ == "__main__":
    main()
